### ISSUE TITLE
@all-contributors

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/in-quiz-questions#11]
@all-contributors please add @monkrus for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @ajmeese7 for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @monkrus  for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @Nazarov7mu for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @monkrus for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @monkrus for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @Ebazhanov  for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @monkrus for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @Ebazhanov @monkrus @ajmeese7 @Nazarov7mu @amitykaran @santhosh-techie @iamjake-dev @azdemir @arqarq for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @monkrus for code, fundingFinding, ideas

**Comment by Ebazhanov** [comment]
@all-contributors please add @santhosh-techie for code,

**Comment by Ebazhanov** [comment]
@all-contributors please add @iamjake-dev for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @azdemir for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @arqarq for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @amitykaran for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @ajmeese7 for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @Nazarov7mu for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @add-ajmeese7 for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @azdemir for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @arqarq for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @amitykaran for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @azdemir for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @arqarq for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @ajmeese7 for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @9Nazarov7mu for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @9Nazarov7mu for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @Nazarov7mu for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @saurav1423 content

**Comment by Ebazhanov** [comment]
@all-contributors please add @Chetan11-dev for content

**Comment by Ebazhanov** [comment]
@all-contributors please add @SeniorHunter for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @SergDaut for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @goodday451999 for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @AbhiSaphire for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @gmonu for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @kenkyusha for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @juandavidtowers for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @cyber-netics for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @jtrisw for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @ingenium21  for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @jtrisw for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @fantypants for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @roplayer  for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @igielskv for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @faraztanveer  for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @mohnishkarri for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @andyzhu for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @kushvishal  for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @7fold  for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @Swetabhsuman8 for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @theInvincible for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @mehmeteyesin for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @lok0613  for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @adriadejuan  for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @gl-man for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @Jheel-patel  for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @wsameer  for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @alexander-e-andrews  for design

**Comment by abmaxwell** [comment]
Q.31 is incorrect. Per https://www.w3schools.com/js/js_reserved.asp "Catch", "Function" and "This" are reserved words while "array" is not.

**Comment by Ebazhanov** [comment]
Hi, @abmaxwell! Good catch please create pull request will merge it then!

**Comment by Ebazhanov** [comment]
@all-contributors please add @abmaxwell  for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @SlavaSD for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @mayurbiw  for design

**Comment by Mascantosh** [comment]
@all-contributors please add @Mascantosh for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @kivancbeser for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @Ritika-Das for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @Mascantosh for code, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @Ritika-Das for design, ideas, talk

**Comment by Ebazhanov** [comment]
@all-contributors please add @Mascantosh for talk, ideas, content

**Comment by Ebazhanov** [comment]
@all-contributors please add @Zer07793 for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @Zer07793 for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @cheungdzinyung  for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @sadhac for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @tainenko for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @github-star-coder for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @danilotecoliveira for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @lordeko for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @TheShubham-K  for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @reza1615  for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @testtree for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @cherylli  for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @TechieTom  for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @aHishamm for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @Dakshitha96 for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @BADRKAC  for design

**Comment by Dakshitha96** [comment]
Thank you for approval!


Dakshitha Dissanayaka 
BICT(Hons) in Software Technology
 South Eastern University
 Contact - (+94)71 10 35 170
dakshithadissanayaka96@gmail.com
dakshithadissanayaka@icloud.com
LinkedIn - http://linkedin.com/in/dakshitha-dissanayaka-099a09143

**Comment by Ebazhanov** [comment]
@all-contributors please add @DarkAlexWang for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @maximlangman for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @GordonGrant for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @ephremdeme for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @JonOrcutt for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @topdev10 for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @cookwellwebsite  for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @xren935 for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @nemo369 for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @mdsaifalam96  for design

**Comment by Ebazhanov** [comment]
@all-contributors please add @borosilva  for design
