### ISSUE TITLE
Missing question in python skill test.

### ISSUE THREAD

**Issue by rishabhjain05** [Ebazhanov/in-quiz-questions#116]
I passed the quiz, but there was a missing question. I have taken the screenshot. Please update your inventory.  

~ Thank You :-)
![Annotation 2020-07-12 102305](https://user-images.githubusercontent.com/36572497/87239276-fbc6c600-c42a-11ea-848e-ea8398f7a8e9.jpg)

**Comment by Ebazhanov** [comment]
thanks for the info, well done congrats! I have updated python-quiz based on your screenshot.
FYI [https://github.com/Ebazhanov/in-quiz-questions/blob/master/python/python-quiz.md](https://github.com/Ebazhanov/in-quiz-questions/blob/master/python/python-quiz.md)
