### ISSUE TITLE
Python : Question 29 

### ISSUE THREAD

**Issue by mayurbiw** [Ebazhanov/in-quiz-questions#148]
Q29. When does a for loop stop iterating?
 when it encounters an infinite loop
 when it encounters an if/else statement that contains a break keyword
 when it has assessed each item in the iterable it is working on or a break keyword is encountered
 when the runtime for the loop exceeds O(n^2)

Option 2 is marked as the right answer. Obviously it is wrong. 

Taking the simple example 
l = [1,2,3,4]
for i in l:
  print(i)

It does not have if/else, however, it will stop iterating once all the elements in the iterable are finished. 
There fore **option 3 (when it has assessed each item in the iterable it is working on or a break keyword is encountered)** is correct.

**Comment by Ebazhanov** [comment]
Thank you @mayurbiw FYI your PR was merged 
https://github.com/Ebazhanov/in-quiz-questions/pull/149
