### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by testtree** [Ebazhanov/in-quiz-questions#205]
Please upload this file for AWS. also you need to create a folder for AWS
[aws.txt](https://github.com/Ebazhanov/in-quiz-questions/files/5012129/aws.txt)

**Comment by Ebazhanov** [comment]
Thank you for the changes in attach file, if you want you can do it by yourself.

**Comment by testtree** [comment]
Please add all my issues reports, yourself. Thanks
