### ISSUE TITLE
In React.js Assessment: Qustions 17 and 36 are the same

### ISSUE THREAD

**Issue by nemo369** [Ebazhanov/in-quiz-questions#263]
In React.js Assessment: Qustions 17 and 36 are the same ->
but they have different correct answer and I'm not sure which wone is the correct one?

17. What do you call the message wrapped in curly braces below?
let message = "Hi there";
const element = <p>{message}</p>

    1. a JS function
    2. a JS element
    3 .a JS expression <<<<<--CORRECT
    4 . a JSX wrapper <<<<<--CORRECT
is it 3 or 4?

**Comment by Ebazhanov** [comment]
Thank you once again for submitting the issue, yes it really good question and for your info, I have created request on https://stackoverflow.com/questions/63337132
