### ISSUE TITLE
Python: question 23

### ISSUE THREAD

**Issue by Wingman4l7** [Ebazhanov/in-quiz-questions#278]
Correct answer should be `my_game = Game()` not the current `my_game = (Game)`.

**Comment by Ebazhanov** [comment]
Hello, @Wingman4l7!

Could you please check the rest of the answers related to the question
![image](https://user-images.githubusercontent.com/13170022/94988239-05fcea00-056c-11eb-98db-919cba37360e.png)
your suggested answer does not match any from the existing one.
Thank you in advance!

**Comment by hridyakrishna** [comment]
@Wingman4l7 Isn't the current answer already 'my_game = Game()' ?

**Comment by Wingman4l7** [comment]
No, it's currently the wrong answer:

- [x] `my_game = class(Game)`
- [ ] `my_game = Game()`

**Comment by Ebazhanov** [comment]
Ok, give us the right answer, please!

**Comment by Wingman4l7** [comment]
The correct answer is 
`my_game = Game()`

**Comment by Ebazhanov** [comment]
ok, but what should i do? Add this new correct one or select something close to correct answer from 4 suggested (see on my screenschot above)

**Comment by Wingman4l7** [comment]
I think the answers were transcribed incorrectly from the original question; none of them are correct.

**Comment by Ebazhanov** [comment]
Thanks, @Wingman4l7 I add your correct answer at the end 
FYI 
![image](https://user-images.githubusercontent.com/13170022/95160534-22359c80-07a1-11eb-9acf-411594ed010c.png)
and updated directly to master.

Have a good productive day!
