### ISSUE TITLE
new Python question not in list (linear runtime)

### ISSUE THREAD

**Issue by Wingman4l7** [Ebazhanov/in-quiz-questions#279]
![Screen Shot 2020-08-13 at 8 02 59 PM](https://user-images.githubusercontent.com/1383561/90210073-ef26ec00-dda1-11ea-980b-300299143af8.png)

**Comment by Dhanush-Garrepalli** [comment]
The amount of time it takes the function to complete grows linearly as the input size increases

**Comment by Wingman4l7** [comment]
Here is the text of the question and answers in Markdown so a PR can be made and the question can be added:

#### Q53. What does it mean for a function to have linear runtime?
- [ ] `You did not use very many advanced computer programming concepts in your code.`
- [ ] `The difficulty level your code is written at is not that high.`
- [ ] `It will take your program less than half a second to run.`
- [x] `The amount of time it takes the function to complete grows linearly as the input size increases.`

**Comment by Ebazhanov** [comment]
Thank you Guys! @Wingman4l7 @Dhanush-Garrepalli 
FYI I added it directly to [master](https://github.com/Ebazhanov/in-quiz-questions/blob/28a04e3f4a5bdedc53de40605dce7db185511be7/python/python-quiz.md#L573-L573), but it was a good idea to create PR
