### ISSUE TITLE
new Python question not in list (defining function)

### ISSUE THREAD

**Issue by Wingman4l7** [Ebazhanov/in-quiz-questions#280]
![Screen Shot 2020-08-13 at 8 03 20 PM](https://user-images.githubusercontent.com/1383561/90210141-0f56ab00-dda2-11ea-8c2b-6a0d112489a1.png)

**Comment by Dhanush-Garrepalli** [comment]
def getMaxNum(list_of_nums) : 
    # body of function goes here

**Comment by Ebazhanov** [comment]
@Wingman4l7 thanks for the new question and feel free to add PR if you have something to update
FYI added directly to [master](https://github.com/Ebazhanov/in-quiz-questions/blob/94a9553f63b3333697282e2a2f029e1128e3a707/python/python-quiz.md#L579-L579)
