### ISSUE TITLE
new Javascript question not in list (program problem)

### ISSUE THREAD

**Issue by Wingman4l7** [Ebazhanov/in-quiz-questions#292]
![Screen Shot 2020-08-17 at 10 43 33 AM](https://user-images.githubusercontent.com/1383561/90428491-ede31100-e078-11ea-93af-ba5f595acb26.png)

**Comment by flyingSquirrel-dev** [comment]
Can I take this issue? :)

**Comment by Wingman4l7** [comment]
@flyingSquirrel-dev I'm OK with it, go for it!

**Comment by flyingSquirrel-dev** [comment]
However, I can't find any problem with the code above. JavaScript Engine is able to read correctly, isn't it?
`The condition in the ternary is using the assignment operator.` might be the answer for this quiz I guess.

**Comment by Ebazhanov** [comment]
@Wingman4l7 thank you for raising the issue 
@flyingSquirrel-dev thank you for the suggestion FYI already in [master](https://github.com/Ebazhanov/in-quiz-questions/blob/94a9553f63b3333697282e2a2f029e1128e3a707/javascript/javascript-quiz.md#L438-L438)
