### ISSUE TITLE
new Javascript question not in list (error keyword)

### ISSUE THREAD

**Issue by Wingman4l7** [Ebazhanov/in-quiz-questions#293]
![Screen Shot 2020-08-17 at 10 46 59 AM](https://user-images.githubusercontent.com/1383561/90428549-018e7780-e079-11ea-9225-6da6c7b628f5.png)

**Comment by flyingSquirrel-dev** [comment]
Can I get this issue?

**Comment by Wingman4l7** [comment]
@flyingSquirrel-dev I'm OK with it, go for it!

**Comment by Ebazhanov** [comment]
@Wingman4l7 thank you for the issue and @flyingSquirrel-dev thank you I that you already updated it
![image](https://user-images.githubusercontent.com/13170022/94988629-e0251480-056e-11eb-9638-1a752a05c05c.png)
Great job, guys!!!
