### ISSUE TITLE
new Javascript question not in list (async / defer)

### ISSUE THREAD

**Issue by Wingman4l7** [Ebazhanov/in-quiz-questions#294]
![Screen Shot 2020-08-17 at 10 47 57 AM](https://user-images.githubusercontent.com/1383561/90428590-10752a00-e079-11ea-9b08-7ed30e5540fc.png)

**Comment by flyingSquirrel-dev** [comment]
Hi there! :) 
Can I take this?

**Comment by Wingman4l7** [comment]
Fine by me, I wasn't going to put in a pull request to add it anytime soon.

**Comment by Wingman4l7** [comment]
@flyingSquirrel-dev Fine by me, I wasn't going to put in a pull request to add it anytime soon.

**Comment by Ebazhanov** [comment]
Guys great teamwork! @Wingman4l7 @flyingSquirrel-dev 
![image](https://user-images.githubusercontent.com/13170022/94988667-33976280-056f-11eb-91d8-1eeb31e97a87.png)
