### ISSUE TITLE
new Java question not in list (OOP)

### ISSUE THREAD

**Issue by Wingman4l7** [Ebazhanov/in-quiz-questions#299]
![Screen Shot 2020-08-17 at 4 17 57 PM](https://user-images.githubusercontent.com/1383561/90453473-8d1dfd80-e0a5-11ea-8a8a-27b952990503.png)

**Comment by Ebazhanov** [comment]
FYI @Wingman4l7 added directly to [master](https://github.com/Ebazhanov/in-quiz-questions/blob/63588746196d255362b4dab423769d946a433c8d/java/java-quiz.md#L382-L382), thanks!

**Comment by Ebazhanov** [comment]
@all-contributors please add @Wingman4l7 for design
