### ISSUE TITLE
Nodejs quiz - question #21

### ISSUE THREAD

**Issue by mlito** [Ebazhanov/in-quiz-questions#310]

**Comment by mlito** [comment]
Hello Evgenii 
I created separate branch (mlito_dev) locally. 
Tried to push it and then to create pull request . 
But while performing push for mlito_dev I got error : 

remote: Permission to Ebazhanov/in-quiz-questions.git denied to mlito.
fatal: unable to access 'https://github.com/Ebazhanov/in-quiz-questions.git/': The requested URL returned error: 403
Pushing to https://github.com/Ebazhanov/in-quiz-questions.git

Do I need some permissions ? 
Thanks in advance

**Comment by Ebazhanov** [comment]
this is a very common issue, what I suggested to do is: 
- first, check that you have clicked on  button `Fork` in GitHub for this repository
![image](https://user-images.githubusercontent.com/13170022/91017104-0fe71100-e5ee-11ea-9810-5af8e60ac4ff.png)
- if you still have the same error please clone this repo one more time to the different local folder with different name and try to push from this new location.
if you still have the same issue please let me know

**Comment by mlito** [comment]
Thanks .
Now It succeeded . I created pull request
