### ISSUE TITLE
Lot of missing questions in the C++

### ISSUE THREAD

**Issue by tusharnankani** [Ebazhanov/in-quiz-questions#318]
Hi!
I just gave the LinkedIn assessment test, for C++; and a lot of questions were missing (hardly 1 - 2 questions were in this repositories), hence, opening this issue.
PS: I passed the 70th percentile.

Regards,
Tushar Nankani

**Comment by Ebazhanov** [comment]
@tusharnankani congratulation with your passed assessment! Feel free to create PR with any updates.
