### ISSUE TITLE
Incorrect git question?

### ISSUE THREAD

**Issue by MagicLegend** [Ebazhanov/in-quiz-questions#320]
I was reading the `git` answers when I read this:

https://github.com/Ebazhanov/in-quiz-questions/blob/master/git/git-quiz.md#q56-which-key-press-return-a-set-of-suggestions-to-pick-from--when-writing-a-git-command

It states that auto-complete can be achieved with `shift`. In what context would this be? Isn't the universal auto-complete `tab`?

**Comment by n3wborn** [comment]
> I was reading the `git` answers when I read this:
> 
> https://github.com/Ebazhanov/in-quiz-questions/blob/master/git/git-quiz.md#q56-which-key-press-return-a-set-of-suggestions-to-pick-from--when-writing-a-git-command
> 
> It states that auto-complete can be achieved with `shift`. In what context would this be? Isn't the universal auto-complete `tab`?

You're right, and there's many other mistakes, at least 3, and I've stopped at Q35...

**Comment by Ebazhanov** [comment]
@LeoMajorR thank you for the fix -> will close the issue then! Have a good day!
