### ISSUE TITLE
Missing questions for Agile Methodologies

### ISSUE THREAD

**Issue by rveldhuis** [Ebazhanov/in-quiz-questions#351]
I was asked:

When the team needs to make a decision, what is the best course of action?
-Try to achieve concensus. //Answer?
-Take a vote and the majority rules.
-Identify the person who is most knowledgeable and ask them to decide.
-Let the most senior member of the team decide.

Which action is something the Team Facillitator should NOT do?
-Embrace servant leadership.
-Estimate story points. //Answer?
-Celebrate successes.
-Remove impediments

A team needs to do research, design, prototyping. What is this type of story called?
-Exploratory spike
-Backlog refinement
-Functional decomposition
-R&D

Which story about technical debt is true?
-Technical debt is another name for bugs
-It is at the Product Owner's descretion to allocate effort to reduce technical debt.
-Adding technical debt should be avoided at all costs. //Answer?
-Technical debt is what the Product Owner owes to the developers if they work a lot of overtime to complete the sprint.

Im not 100% sure about the answers I gave.

**Comment by Ebazhanov** [comment]
@rveldhuis thank you for the input! I added your questions directly to [master](https://github.com/Ebazhanov/in-quiz-questions/blob/63588746196d255362b4dab423769d946a433c8d/agile-methodologies/agile-methodologies-quiz.md#L214-L214), feel free to PR's by yourself.
