### ISSUE TITLE
New Skills

### ISSUE THREAD

**Issue by chilcot** [Ebazhanov/in-quiz-questions#359]
Power BI

A dataset that includes _ can be used to create a map visualization. (Select all that apply.) 

A. house numbers, street names 
B. geospatial data 
C. city names, country names 
D. longitude, latitude 

[ ] A, B, C, D 

[ ] A, C, D 

[ ] B, C, D 

[ ] D

How do you create a chart visual in Power Bl Desktop Report view? (Select all that apply.) 

A. Click New Visual on the Home tab. 

B. Select a chart visual in the Visualizations pane. 

C. Click New Visual on the Data Tools tab. 

D. Select a field that contains values. 

[ ] A, B, or D 
[ ] B or D 
[ ] B orC 
[ ] A or B

What daily sales number does this DAX measure formula calculate? CALCULATE(SUM([Sales]) ,DATESHTD([Date] )) 

[ ] running total sales in each month that starts over each month 

[ ] total sales for the entire month 

[ ] running total in entire year for the entire month 

[ ] rolling average over 12 months of sales

You are creating a report in Power Bl Desktop and want to restrict the data to records where Country="Canada". To accomplish this, what do you need to create? 

[ ] a directive 

[ ] a custom column 

[ ] an indexed column 

[ ] a parameter

What is the primary benefit of using visualizations such as line charts, bar charts, and column charts? 

[ ] They are easier to create than other visualizations. 
[ ] They require fewer resources than more complex visualizations. 
[ ] They are also used in Excel, so they feel familiar to users. 
[ ] They are free to use.

In Power Bl service, deleted pages are available after deletion until 

[ ] midnight of the day on which they are deleted 
[ ] the next billing cycle 
[ ] you empty the Recycle Bin 
[ ] the report has been saved

You need to add a required color to a bar chart. How can you add an exact color value to an existing bar chart? 

[ ] Click the color in the visual (e.g., the bars) and right-click to select the color. 
[ ] You cannot select custom colors in a bar chart or related visual. 
[ ] Select the value closest to this color from the color formatting options. 
[ ] Enter the hex value into the color formatting options.

The Excel function IF is nearly the same as which DAX function? 

[ ] SWITCH 
[ ] IF 
[ ] IFX 
[ ] IFS

Consider the Power Bl extract, transform, and load process (ETL). During this process, data is read and then

[ ] stored in SQL Server 
[ ] written to an OLAP cube 
[ ] assigned a data type 
[ ] sorted by primary key

Power Bl's Publish to Web option allows you to embed visualizations within _. (Select all that apply.) 

A. blog posts 

B. email messages C. web sites 

D. text messages 

[ ] A,C 

[ ] C 

[ ] A, B, C 

[ ] A, B, C, D 

What can you do within the Power Bl Desktop Query Settings pane? (Select all that apply.) 

A. Rename a query step. 

B. Delete a query step. 

C. Delete from one query step to the end. 

D. Reorder the steps. 

[ ] B, C, D 

[ ] A, B, C, D 

[ ] A, B, D 

[ ] A, B, C

After you enter text in the Q&A box or O&A visual, Power Bl will _ your data to create a list of appropriate visualizations. 

[ ] filter and group 

[ ] sort and filter 

[ ] sort, filter, and group 

[ ] sort and group

**Comment by Ebazhanov** [comment]
@chilcot thanks! FYI all the questions already in the [repository](https://github.com/Ebazhanov/in-quiz-questions/blob/eb56596063d669a579df10277e3d3174a0317dbd/microsoft-power-bi/microsoft-power-bi-quiz.md#L2-L2)!
