### ISSUE TITLE
New Questions for Object-Oriented Programming (OOP)

### ISSUE THREAD

**Issue by vin-lz** [Ebazhanov/in-quiz-questions#363]
What best describes what object-oriented programming does?
[ ] It focuses on objects that interact cleanly with one another.
[ ] It programs exclusively to interfaces.
[ ] It programs exclusively to classes.
[ ] It creates one class for all business logic.

Can abstract classes be used in multilevel inheritance?
[ ] No, abstract classes can be used only in single-level inheritance since they must be immediately implemented.
[ ] yes, always
[ ] yes, but with only one abstract class
[ ] No, abstract classes do not have constructors.

Why is inheritance used when creating a new class?
[ ] to delegate coding responsibilities more efficiently
[ ] to conserve memory
[ ] to protect attributes from unwanted changes
[ ] to avoid writing duplicate code

How are the contents of a composition different from those of an aggregation?
[ ] The contents fo a composition are all siblings.
[ ] An aggregation contains only abstract classes.
[ ] If a composition dies, the contents die.
[ ] If one element of an aggregation is dereferenced, all its elements are eligible for garbage collection.

What is the relationship between abstraction and encapsulation?
[ ] Abstraction is about making relevant information visible, while encapsulation enables a programmer to implement the desired level of abstraction.
[ ] Abstraction and encapsulation are essentially the same.
[ ] Abstraction and encapsulation are unrelated.
[ ] Encapsulation is about making relevant information visible, while abstraction enables a programmer to implement the desired level of encapsulation.

**Comment by Ebazhanov** [comment]
@vin-lz Thank you for the issue -> I added your questions to [object-oriented-programming-quiz.md](https://github.com/Ebazhanov/in-quiz-questions/blob/fe82b034b05e3b122a61e75b046c08400c32fd90/oop/object-oriented-programming-quiz.md#L276-L276)
