### ISSUE TITLE
The largest collection questions/answers for different quizzes in .XLSX

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/in-quiz-questions#381]
if anyone is interested in here is [LinkedIn_Skill_Exams.xlsx](https://github.com/Ebazhanov/in-quiz-questions/files/5250106/LinkedIn_Skill_Exams.xlsx) the largest collection of questions/answers to different quizzes

**Comment by tik9** [comment]
Should we close the issue and remove the file from GH?

**Comment by Ebazhanov** [comment]
Hello, @tik9 I think you are right this issue has opened a long time ago, thanks for the comment, I will close it.
