### ISSUE TITLE
CSS, Question 32 is wrong about precedence

### ISSUE THREAD

**Issue by HoraceShmorace** [Ebazhanov/in-quiz-questions#383]
```
Q32. Which type of declaration will take precedence?
  any declarations in user-agent stylesheets <<<<---Correct
  important declarations in user stylesheets
  normal declarations in author stylesheets
  important declarations in author stylesheets
```
That's wrong. In fact, declarations in user-agent stylesheets have the lowest precedence. Otherwise, no other CSS would have any effect.

"Important declarations in user stylesheets" have the highest precedence, per [the CSS2 spec](https://www.w3.org/TR/CSS2/cascade.html).

**Comment by Ebazhanov** [comment]
@HoraceShmorace thank you for the details explanation FYI added the reference [link](https://github.com/Ebazhanov/in-quiz-questions/blob/f14db34e3675402d4ae442b9b7c63eeaffe0ac35/css/css-quiz.md#L343-L343) in front of your answer
