### ISSUE TITLE
Couple of new questions to Machine Learning

### ISSUE THREAD

**Issue by prateekagrawaliiit** [Ebazhanov/in-quiz-questions#397]
Hello

I have a couple of questions I came across while giving a machine learning assessment and I could not find them here. Please let me know how can I help in updating the file

**Comment by monkrus** [comment]
Hello @prateekagrawaliiit The best way to help is to update those answers and creating a pull request. You can use your skills, YouTube videos, Reddit, etc. Thank you for your future contributions!

**Comment by edo92** [comment]
Lot of answers are wrong.

**Comment by monkrus** [comment]
@edo92 Would you like to contribute with a new PR?
