### ISSUE TITLE
Q38. What prints to the console when this code is executed? C#

### ISSUE THREAD

**Issue by Betoxx1** [Ebazhanov/in-quiz-questions#414]
Just checked the C# code and the nearest correct answer is answer 3.

There is something wrong with the code. It will throw an error because you cant apply Inheritance to methos that way.

 [*] an error, because the method signature of Login doesn't match the delegate

**Comment by Ebazhanov** [comment]
@Betoxx1 Thank you I added your explanation inside this [question](https://github.com/Ebazhanov/in-quiz-questions/blob/master/c%23/c-sharp-quiz.md)
