### ISSUE TITLE
Q39. How would you declare a sealed class named User? C#

### ISSUE THREAD

**Issue by Betoxx1** [Ebazhanov/in-quiz-questions#415]
The correct answer is: sealed class User
sealed classes does not need to be private.

[*] sealed class User

**Comment by Ebazhanov** [comment]
thank you @Betoxx1 
Updated 
![image](https://user-images.githubusercontent.com/13170022/94989329-3fd1ee80-0574-11eb-9146-f4fa06b0af55.png)
