### ISSUE TITLE
Java Question 16 Doesnot exist

### ISSUE THREAD

**Issue by Betoxx1** [Ebazhanov/in-quiz-questions#416]

**Comment by Ebazhanov** [comment]
No description provided.
Closed

**Comment by Betoxx1** [comment]
Hi, I see that you closed the issue. What happen is that the question 16 in java does not appear is that an error?

**Comment by Ebazhanov** [comment]
@Betoxx1 you are right, thank you -> [UPDATED](https://github.com/Ebazhanov/in-quiz-questions/blob/master/java/java-quiz.md)

**Comment by Ebazhanov** [comment]
@all-contributors please add @Betoxx1 for design
