### ISSUE TITLE
More questions for jQuery with some for-sure answers

### ISSUE THREAD

**Issue by jadeutsch** [Ebazhanov/in-quiz-questions#510]
Effects like show, hide, fadIn, and fadeOut can be called with no arguments, but can also take arguments for how long they should last. Which is NOT a duration argument supported by these functions?
- "fast"
- "extreme" <-- Correct
- 2000
- "slow"

----------------------------------------------------------------------------------------------------------------------------

Though jQuery offers visual effects, it is considered a best practice to use CSS to se up different states triggered by classes, where it makes sense. What's the easiest way to enable and disable a class `bounce` on an element with the ID `dialog`?
- `$('#dialog').classToggle('bounce')`
- `$('#dialog.bounce').removeClass().addClass()`
- `$(#dialog').addOrRemoveClass('bounce')`
- `$(#dialog').toggleClass('bounce')` <-- Correct

----------------------------------------------------------------------------------------------------------------------------

What is the main difference between selectors and filters?
- Selectors are used to refine the content that filters have been applied to.
- Selectors are used to find and select content in a page. Filters are used to refine the results of selectors. <-- Correct
- Filters are used to remove content from the page. Selectors are used to add content to the page
- There is no real difference. They are both used to build up lists of page content.

----------------------------------------------------------------------------------------------------------------------------

You want to create a custom right-click menu. How might you start the code?
- `$('#canvas').on('click.right', function(){ console.log('Handled a right-click') });`
- `$('#canvas').on('contextual', function(){ console.log('Handled a right-click') });`
- `$('#canvas').on('contextmenu', function(){ console.log('Handled a right-click') });`
- `$('#canvas').on('rightclick', function(){ console.log('Handled a right-click') });`

----------------------------------------------------------------------------------------------------------------------------

What is the correct way to check how many paragraphs exist on a page using jQuery?
- `$('p').count()`
- `$('p').length` <-- Correct
- `$('*').find('p')`
- `$('p').length()`

**Comment by Ebazhanov** [comment]
@jadeutsch thanks for the great input, I added it directly to [master](https://github.com/Ebazhanov/in-quiz-questions/blob/17e319096e93017cff1ab13e71def75e72a71f86/jquery/jquery-quiz.md#L527-L527)!

**Comment by Ebazhanov** [comment]
@all-contributors please add @jadeutsch for design, code
