### ISSUE TITLE
Add label hacktoberfest

### ISSUE THREAD

**Issue by shriyaMadan** [Ebazhanov/in-quiz-questions#517]
I am bringing this to your knowledge that contributes to this repository is not counting in the Hacktoberfest as there is no label of Hacktoberfest
PS: "hacktoberfest2020" is not an acceptable label under Hacktoberfest guidelines.

**Comment by Ebazhanov** [comment]
You are right, but there also wiritten that you can `Submit your PR in a repo with the hacktoberfest topic!`

```
PRs count if:
Submitted during the month of October AND
Submitted in a public repo AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
)
```

===>>>> [reference link ](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by shriyaMadan** [comment]
yeah, that's what I wrote

> You are right, but there also wiritten that you can `Submit your PR in a repo with the hacktoberfest topic!`
> 
> ```
> PRs count if:
> Submitted during the month of October AND
> Submitted in a public repo AND (
>   The PR is labelled as hacktoberfest-accepted by a maintainer OR
>   Submitted in a repo with the hacktoberfest topic AND (
>     The PR is merged OR
>     The PR has been approved
>   )
> )
> ```
> 
> ===>>>> [reference link ](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

yeah, that's what I wrote.

> You are right, but there also wiritten that you can `Submit your PR in a repo with the hacktoberfest topic!`
> 
> ```
> PRs count if:
> Submitted during the month of October AND
> Submitted in a public repo AND (
>   The PR is labelled as hacktoberfest-accepted by a maintainer OR
>   Submitted in a repo with the hacktoberfest topic AND (
>     The PR is merged OR
>     The PR has been approved
>   )
> )
> ```
> 
> ===>>>> [reference link ](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

Yeah, that's what I wrote.

**Comment by shriyaMadan** [comment]
> You are right, but there also wiritten that you can `Submit your PR in a repo with the hacktoberfest topic!`
> 
> ```
> PRs count if:
> Submitted during the month of October AND
> Submitted in a public repo AND (
>   The PR is labelled as hacktoberfest-accepted by a maintainer OR
>   Submitted in a repo with the hacktoberfest topic AND (
>     The PR is merged OR
>     The PR has been approved
>   )
> )
> ```
> 
> ===>>>> [reference link ](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

Yeah, that's what I wrote.

**Comment by Ebazhanov** [comment]
FYI @shriyaMadan updated your PR according to requirements -> hacktoberfest
