### ISSUE TITLE
Automatic question answer DATA

### ISSUE THREAD

**Issue by LucasLermagne** [Ebazhanov/in-quiz-questions#524]
The more I look at the source code of the quiz still pages, the more I tell myself that it is possible to retrieve the questions and answers automatically. Indeed Linkedin has taken away our access to highlight the sentences and therefore impossible to copy and paste them. But serious to the source code I can copy and paste the questions and answers. The problem being that it still takes time and I think it's possible to automate it. Either with an Exel VBA macro or with a Python script or something else.

Here is some more information:

assessment-a11y-title (paragraph id withe title)
sa-assessment-quiz__title-detail (additional detail to the title)

sa-question-basic-multichoice__multiline (span with answer)
sa-question-multichoice__input (span answer)

**Comment by tik9** [comment]
Suggestion for closing the issue. Can you send a PR @LucasLermagne ?

**Comment by JAYISAWSM** [comment]
You can use **snipping tool** and capture the question and options at the same time

**Comment by tik9** [comment]
@JAYISAWSM and @LucasLermagne  thanks, I would recommend to check my [repo ](https://github.com/tik9/tesseractToMarkdown)regarding a python converter using a snipping tool, If you want to see further tests, [look here](https://github.com/tik9/pluralsight-skill-test)

**Comment by Ebazhanov** [comment]
Thank you @tik9 for your great participation in this topic! Based on your answers and two examples I will close this issue!
https://github.com/tik9/pluralsight-skill-test
https://github.com/tik9/tesseractToMarkdown
Thank you all, guys! Great job! :muscle:

**Comment by JohnSti** [comment]
@Ebazhanov Do you have Indeed assessments? Or know of where to procure them? Thanks
