### ISSUE TITLE
Microsoft Azure -> more questions

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/in-quiz-questions#547]
![tes5](https://user-images.githubusercontent.com/13170022/95832427-87a60200-0d3a-11eb-89a8-dd1a8b77e22e.jpg)
![tes6](https://user-images.githubusercontent.com/13170022/95832436-8a085c00-0d3a-11eb-9923-d81d28fab601.jpg)
![test1](https://user-images.githubusercontent.com/13170022/95832439-8aa0f280-0d3a-11eb-8234-c16f48e9c3e1.jpg)
![test2](https://user-images.githubusercontent.com/13170022/95832442-8aa0f280-0d3a-11eb-8b09-3588e73e0706.jpg)
![test3](https://user-images.githubusercontent.com/13170022/95832443-8b398900-0d3a-11eb-9ba9-292ec2068a03.jpg)
![test4](https://user-images.githubusercontent.com/13170022/95832444-8b398900-0d3a-11eb-9089-46ef220dc859.jpg)
![test7](https://user-images.githubusercontent.com/13170022/95832445-8b398900-0d3a-11eb-8d21-08481c521aeb.jpg)
![test8](https://user-images.githubusercontent.com/13170022/95832447-8bd21f80-0d3a-11eb-968a-004e2e015729.jpg)

**Comment by tik9** [comment]
Wer can close it.

**Comment by Ebazhanov** [comment]
Ja, Sie haben Recht, diese Fragen sind bereits enthalten, daher werde ich dieses Ticket schließen, danke für Ihren Kommentar
https://github.com/Ebazhanov/in-quiz-questions/blob/master/microsoft-azure/microsoft-azure-quiz.md
