### ISSUE TITLE
C++ quiz

### ISSUE THREAD

**Issue by ShiraStarL** [Ebazhanov/in-quiz-questions#552]
Hi :)

Thank's for this repo it's great!
Some of the answers in C++ quiz are wrong.. here is the right answers:

Q3: The answer is  -->  a) 7 bits

Q4: The answer is  -->  a) Error
Because std::vector v1{1,2,3}; doesn't compile, It should be std::vector<int> v1{1,2,3};

Q7: The answer is --> a) 4
You can see example [here](https://en.cppreference.com/w/cpp/language/union)

Q9: The answer is  -->  c) Error
Same reason as Q4

Q10: The answer is  -->  c) The default access specifier for members of struct is public, where as for member of class , it is private.
You can see the answer [here](https://www.fluentcpp.com/2017/06/13/the-real-difference-between-struct-class/)

Q11: The answer is  -->  a) typedef struct {
		int sunday:1;
		int monday:1;
		// more days 
		int friday:1;
		int saturday:1;
		} weekdays;
That syntax says that each variable size is 1 bit.
'bit' is not a type in C++.

Thank's again !

**Comment by Ebazhanov** [comment]
Thank you for your answers and useful links :+1:! I will push it directly to master!

**Comment by Ebazhanov** [comment]
@all-contributors please add @ShiraStarL for design
