### ISSUE TITLE
JSON needs fixes

### ISSUE THREAD

**Issue by nisozakuto** [Ebazhanov/in-quiz-questions#553]
https://github.com/Ebazhanov/in-quiz-questions/blob/master/json/json-quiz.md
There are a few mistakes in these answers. I will review the answers and create a PR unless someone else notices meanwhile

**Comment by tonchique** [comment]
@Ebazhanov Posted a PR for this one earlier today

**Comment by RobTables** [comment]
Created a PR for this yesterday which at this time is waiting to be accepted. Feel free to review answers in the PR.

**Comment by Ebazhanov** [comment]
Oh, very nice! Thank you all guys! going to check it .....
