### ISSUE TITLE
Machine Learning Q05

### ISSUE THREAD

**Issue by SvenMeyer** [Ebazhanov/in-quiz-questions#731]
Referring to exactly the link provided in Machine Learning Q05:

[https://medium.com/datadriveninvestor/bias-and-variance-in-machine-learning-51fdd38d1f86](https://medium.com/datadriveninvestor/bias-and-variance-in-machine-learning-51fdd38d1f86)

There it states :

"High Bias Low Variance: Models are consistent but inaccurate on average"

so "It was consistently (but) wrong." should be the right answer

**Comment by Daniboy370** [comment]
Hi @SvenMeyer 
I totally agree with you, thus I will fix that mistake and PR.
