### ISSUE TITLE
Machine Learning Q51

### ISSUE THREAD

**Issue by SvenMeyer** [Ebazhanov/in-quiz-questions#732]
Q51. You and your data science team have 1 TB of example data. What do you typically do with that data?

```
[ ] You use it as your training set.
[ ] You label it big data.
[X] You split it into a training set and test set.
[ ] You use it as your test set.
```
Would be my choice ...

**Comment by Daniboy370** [comment]
@SvenMeyer agree >>  fixed 🤙

**Comment by Daniboy370** [comment]
@Ebazhanov issue can be closed once my PR will be confirmed

**Comment by Ebazhanov** [comment]
thank you guys!

**Comment by angelolovatto** [comment]
Is it just me or is the "correct" choice still marked as "You label it big data"? [link](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/machine-learning/machine-learning-quiz.md#q51-you-and-your-data-science-team-have-1-tb-of-example-data-what-do-you-typically-do-with-that-data)

**Comment by Ebazhanov** [comment]
Good questions, to be hones have no idea, sorry @andreeferreira! If you can find proof and post reference link or explanation directly under that question that would be great! Feel free to creat PR
