### ISSUE TITLE
Kotlin is missing 

### ISSUE THREAD

**Issue by naveedahmad99** [Ebazhanov/in-quiz-questions#741]

**Comment by tik9** [comment]
I would close this issue. Maybe someone will do it sometime.

**Comment by naveedahmad99** [comment]
@tik9 Please add this on the read me for missing questions, and then please close this thread

**Comment by Ebazhanov** [comment]
FYI guys I added info about missing questions into [readme](https://github.com/Ebazhanov/in-quiz-questions/blob/f9da51e6e7cdf9977200f1f3977f30fa3e00aa92/README.md#L54-L54) 
Thank you @naveedahmad99 for creating this issue! :muscle:
