### ISSUE TITLE
Node.js Q15 wrong answer

### ISSUE THREAD

**Issue by vsDizzy** [Ebazhanov/in-quiz-questions#772]
Q15. How can you use the promise API with a callback-based function like child_process.exec?
- new Promise(child_process.exec())
- util.promisify(child_process.exec())
- util.promisify(child_process.exec)
- new Promise(child_process.exec) <<<<----Correct

I believe the correct answer should be the 3rd one.
util.promisify(child_process.exec)

**Comment by vsDizzy** [comment]
Q18. If EventEmitter is in scope, which of the following lines of code will have an event emitter emitting a change event?
- EventEmitter.emit(change);
- EventEmitter.new().emit(change);
- (new EventEmitter()).emit(change); <<<<----Correct
- new EventEmitter(change);

Should be the 1st one. Because the EventEmitter is already in scope. No need to create new one.
EventEmitter.emit(change);

**Comment by vsDizzy** [comment]
Q19. Which of the following objects is a stream
- process.uptime
- process.stdout
- process
- Buffer <<<<-----Correct

Should be process.stdout, Buffer is Buffer type.
process.stdout

**Comment by Ebazhanov** [comment]
Hello, @vsDizzy! Thank you for the answers with explanations :+1: I added them directly to [master](https://github.com/Ebazhanov/in-quiz-questions/blob/7177ca12e7914f1ea02b6785121cd46e816b9b6d/node.js/node.js-quiz.md#L135-L135)

**Comment by Ebazhanov** [comment]
@all-contributors please add @vsDizzy for code, design
