### ISSUE TITLE
R (Programming Language) Add question 29 Given DFMerged <- merge(DF1, DF2) and the image below, how manu rows are in DFMerged?

### ISSUE THREAD

**Issue by Artifex00-00** [Ebazhanov/in-quiz-questions#781]
DF1(data frame 1): DF2(data frame 2):
      VarA  VarB      VarA  VarD
1    1       2         1   18   21
2    4       5         2   19   22
3    7       8         3    20  23

[  ] 6
[  ] 9
[  ] 3
[X] 0

**Comment by Ebazhanov** [comment]
Thank you @Artifex00-00 for opening this issue and providing a new question with answer :boom:
FYI I pushed your changes directly to [master](https://github.com/Ebazhanov/in-quiz-questions/blob/e35b2cee3630a6d38c6eb1d99e705e5bbe62b5e5/r/r-quiz.md#L295-L295)
