### ISSUE TITLE
Windows Server Q44 - I think the answer should be Hardware Security Module

### ISSUE THREAD

**Issue by frexcuadillera** [Ebazhanov/in-quiz-questions#801]

**Comment by Ebazhanov** [comment]
Hello, @frexcuadillera thank you for your suggestion :punch:, I made changes directly into [master](https://github.com/Ebazhanov/in-quiz-questions/blob/3827265dac2fe272cfc5a3d9eb62686d10824c94/windows-server/windows-server-quiz.md#L316-L316), if you have any other ideas of answers your PR's are very welcome! :wave:

**Comment by Ebazhanov** [comment]
@all-contributors please add @frexcuadillera for design
