### ISSUE TITLE
Correction in the option for the question

### ISSUE THREAD

**Issue by amitravikumar** [Ebazhanov/in-quiz-questions#826]
Q3. Which shell query displays all citizens with an age greater than or equal to 21?
db.citizens.select('WHERE age >= 21')
db.citizens.select('age >= 21')
db.citizens.select('WHERE age >= 21')
db.citizens.select **({age: {$qte: 21}})** <<<<<----CORRECT

The correct option for the following question is:
 db.citizens.select **({age: {$gte: 21}})** <<<<<----CORRECT

Point updated is highlighted or bold marked.

**Comment by Ebazhanov** [comment]
Solved, thank you for PR @amitravikumar once again! Good job :boom: https://github.com/Ebazhanov/in-quiz-questions/pull/851
