### ISSUE TITLE
CSS Questions and Answers

### ISSUE THREAD

**Issue by mohnishkarri** [Ebazhanov/in-quiz-questions#89]
The CSS Questions mentioned here do not match the ones asked  in the test . Please update the question with answers as soon as possible .

**Comment by mohnishkarri** [comment]
> Hello @mohnishkarri , thank you for submitting an issue!

@Ebazhanov can I be allowed to modify the css-quiz.md file to add more questions and answers to it

**Comment by Ebazhanov** [comment]
yes sure, you can create PR and add there your changes. And yes you are right I have to create some guidelines on how to get do it properly (maybe today)

**Comment by mohnishkarri** [comment]
> yes sure, you can create PR and add there your changes. And yes you are right I have to create some guidelines on how to get do it properly (maybe today)

can i be added as a contribute too

**Comment by Ebazhanov** [comment]
> Currently working on the repo forked by me . Will create a pull request after i am done with my work. Can I be added as a contribute too please.

yes, 100%

**Comment by mohnishkarri** [comment]
have created pull request . Kindly check and update css-quiz.md as soon as possible . will be updated answers as soon as possible( Mostly tommorrow).

**Comment by Ebazhanov** [comment]
have just merged your PR 👍 and you were added as the contributor, congratulation! 💥

**Comment by Ebazhanov** [comment]
if you think those two were incorrectly created 
[/pull/98](https://github.com/Ebazhanov/in-quiz-questions/pull/98)
[/pull/97](https://github.com/Ebazhanov/in-quiz-questions/pull/97)
please close them

**Comment by mohnishkarri** [comment]
yeah! i guess those were incorrectly and closed them.

**Comment by Ebazhanov** [comment]
solved, thank you @mohnishkarri

**Comment by mohnishkarri** [comment]
Will be working on more . I am happy to contribute to to the project and will contribute more.
