### ISSUE TITLE
JavaScript assessment question 11

### ISSUE THREAD

**Issue by MahmoudAliEng** [Ebazhanov/in-quiz-questions#93]
The correct answer for the 11th question in the JavaScript Assessment is the 2nd answer not the 3rd.
Could you create me a branch to correct this issue and add new questions in Python and JavaScript assessment, please ?

**Comment by Ebazhanov** [comment]
Hello, @MahmoudAliEng! Thank you for your interesting question, I am still disappointed what should I do ))) if you have problem of how create PR you can ask google in anytime, for any other questions feel free to ask me!

**Comment by Ebazhanov** [comment]
if think that this issue no need you anymore please close it.
